### ISSUE TITLE
 more demos please ?

### ISSUE THREAD

**Issue by toufikben** [digao-dalpiaz/DzTalkApp#1]
Hello Rodrigo Depiné Dalpiaz
Thank you for the good work you done so far , I was wounding if you can add more example demos about communication between Two user using DzTalkApp 
lets say user1 select user2 to chat with , how would we implement that thanks alot and have a nice day 
ps : Can  DzTalkApp  support Fmx  ? thank you

**Comment by digao-dalpiaz** [comment]
Hi @toufikben 

The **DzTalkApp** component is supposed to use for send data between two running applications in the same user session on Windows environment.

Maybe you are looking for **DzSocket**: It's a component made for send and receive messages between two or more users using client/server scenario, through Network and/or Internet.

Get it here: https://github.com/digao-dalpiaz/DzSocket
_You can simulate chat functionality running two instances of demo app._

Thanks.
Best regards.

**Comment by digao-dalpiaz** [comment]
@toufikben,
I just created a FMX Chat demo application in DzSocket.
Please take a look at: https://github.com/digao-dalpiaz/DzSocket/tree/master/Demos/ChatDemoFMX
